### ISSUE TITLE
eb command not found

### ISSUE THREAD

**Issue by kuriel-trivu** [Cox-Automotive/aws-ebcli#4]
With Gitlab Runner CI/CD throws `eb command not found`

.gitlab-ci.yml
```
... // other stages and configs, then:
deploy:
  stage: deploy
  image: coxauto/aws-ebcli
  dependencies:
    - build
  script:
    - mkdir -p ~/.aws
    - touch ~/.aws/config
    - chmod 600 ~/.aws/config
    - echo "[profile eb-cli]" >> ~/.aws/config
    - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/config
    - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
    - git checkout $CI_COMMIT_REF_NAME
    - git fetch --all
    - git pull
    - eb labs cleanup-versions --force
    - eb deploy
    - echo "DEPLOYMENT OF $CI_COMMIT_REF_NAME IS COMPLETE"
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - master

```
